version: "3.7"

volumes:
  influx-data:

# YAML Anchors

x-deployment-env: &deployment-env
  ENV: ${ENV:-development}
  SG_ENV: ${SG_ENV:-development}
  TZ: $TZ

x-influxdb-api-key: &influxdb-api-key .env.influxdb

x-influxdb-client-env: &influxdb-client-env
  INFLUX_BUCKET: ${INFLUX_BUCKET:-place}
  INFLUX_HOST: ${INFLUX_HOST:-http://influxdb:9999}
  INFLUX_ORG: ${INFLUX_ORG:-PlaceOS}

x-mqtt-client-env: &mqtt-client-env
  MQTT_HOST: ${MQTT_HOST:-mqtt}
  MQTT_PORT: ${MQTT_PORT:-1883}

x-redis-client-env: &redis-client-env
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}

x-rethinkdb-client-env: &rethinkdb-client-env
  RETHINKDB_HOST: ${RETHINKDB_HOST:-rethink}
  RETHINKDB_PORT: ${RETHINKDB_PORT:-28015}
  RETHINKDB_DB: ${RETHINKDB_DB:-place_development}

services:
  test:
    image: placeos/service-spec-runner:${CRYSTAL_VERSION:-1.2.1}
    volumes:
      - ${PWD}/coverage:/app/coverage
      - ${PWD}/shard.lock:/app/shard.lock
      - ${PWD}/shard.yml:/app/shard.yml
      - ${PWD}/lib:/app/lib
      - ${PWD}/spec:/app/spec
      - ${PWD}/src:/app/src
    depends_on:
      - mqtt
      - redis
      - rethink
      - influxdb
    env_file:
      - *influxdb-api-key
    environment:
      # Environment
      GITHUB_ACTION: ${GITHUB_ACTION:-}
      # Service Hosts
      << : *influxdb-client-env
      << : *mqtt-client-env
      << : *redis-client-env
      << : *rethinkdb-client-env
      # Environment
      << : *deployment-env

  influxdb:
    image: influxdb:${INFLUXDB_IMAGE_TAG:-2.0-alpine}
    restart: always
    hostname: influx
    healthcheck:
      test: influx bucket list
    volumes:
      - type: volume
        source: influx-data
        target: /root/.influxdbv2
    command: "--reporting-disabled"

  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    hostname: mqtt
    environment:
      TZ: $TZ

  redis:
    image: eqalpha/keydb
    restart: always
    hostname: redis
    environment:
      TZ: $TZ

  rethink:
    image: rethinkdb:${RETHINKDB_VERSION:-2.4}
    restart: always
    hostname: rethink
    environment:
      TZ: $TZ
