ARG crystal_version=1.0.0
FROM crystallang/crystal:${crystal_version}-alpine

WORKDIR /app

# Set the commit through a build arg
ARG PLACE_COMMIT="DEV"

# Add trusted CAs for communicating with external services
RUN apk add --update --no-cache ca-certificates bash
RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing watchexec
RUN update-ca-certificates

COPY shard.yml .
COPY shard.override.yml .
COPY shard.lock .

RUN shards install --ignore-crystal-version

COPY scripts/* /app/scripts/

RUN mkdir -p /app/bin/drivers

# These provide certificate chain validation where communicating with external services over TLS
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

CMD /app/scripts/entrypoint.sh
