#! /usr/bin/env bash

image="placeos/init:nightly"

docker pull "${image}"

docker run --rm \
    -e PLACE_EMAIL=${PLACE_EMAIL:-support@place.tech} \
    -e PLACE_PASSWORD=${PLACE_PASSWORD:-test} \
    -v "${PWD}:/tmp/secrets" \
    -w /tmp/secrets -- \
    "${image}" generate-secrets
